# Generated by Django 5.2 on 2025-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
